import { existsSync, readdirSync, readFileSync, statSync } from "node:fs";
import { dirname, join, normalize, resolve } from "node:path";
import {
  currentDocumentationContract,
  formatMib,
} from "./current-documentation-contract.mjs";

const repository = resolve(import.meta.dirname, "..");
const note = "**Note:** This file was generated by ChatGPT 5.6 Sol under the direction of Adam Phillippy.";
const roots = ["README.md", "CHANGELOG.md", "CONTRIBUTING.md", "docs"];
const markdown = [];

function collect(relativePath) {
  const absolutePath = join(repository, relativePath);
  if (statSync(absolutePath).isDirectory()) {
    for (const child of readdirSync(absolutePath).sort()) collect(join(relativePath, child));
  } else if (relativePath.endsWith(".md")) {
    markdown.push(relativePath);
  }
}

for (const root of roots) collect(root);

const failures = [];
function requireText(relativePath, text, description) {
  const contents = readFileSync(join(repository, relativePath), "utf8");
  if (!contents.includes(text)) failures.push(`${relativePath}: ${description}`);
}

function forbidText(relativePath, text, description) {
  const contents = readFileSync(join(repository, relativePath), "utf8");
  if (contents.includes(text)) failures.push(`${relativePath}: ${description}`);
}

for (const relativePath of markdown) {
  const absolutePath = join(repository, relativePath);
  const contents = readFileSync(absolutePath, "utf8");
  if (!contents.split("\n").slice(0, 5).includes(note)) {
    failures.push(`${relativePath}: missing the canonical generated-file note near the top`);
  }

  for (const match of contents.matchAll(/\[[^\]]*\]\(([^)]+)\)/g)) {
    let target = match[1].trim();
    if (target.startsWith("<") && target.endsWith(">")) target = target.slice(1, -1);
    target = target.split("#", 1)[0];
    if (!target || /^(?:https?:|mailto:)/i.test(target)) continue;
    const resolved = target.startsWith("/")
      ? join(repository, target.slice(1))
      : normalize(join(dirname(absolutePath), target));
    if (!existsSync(resolved)) failures.push(`${relativePath}: broken local link ${match[1]}`);
  }
}

let contract;
try {
  contract = currentDocumentationContract(repository);
} catch (error) {
  failures.push(`current implementation contract: ${error instanceof Error ? error.message : String(error)}`);
}

if (contract) {
  const parameterRows = [
    `| Browser sparse correction | ${contract.browserSparseCorrectionSummary} |`,
    `| Imported annotation formats | ${contract.importedAnnotationSummary} |`,
    `| Imported annotation file limit | ${formatMib(contract.annotationLimits.bytes)} |`,
    `| Imported annotation matching-record limit | ${contract.annotationLimits.records.toLocaleString("en-US")} per file |`,
    `| Estimator validation schema | ${contract.validationColumns.length} columns, checked against release TSV |`,
    `| Zoom-axis cache budget | ${formatMib(contract.budgets.zoomAxisBytes)} |`,
    `| Prepared-axis budget | ${formatMib(contract.budgets.preparedAxisBytes)} |`,
    `| Wasm session budget | ${formatMib(contract.budgets.wasmSessionBytes)} |`,
  ];
  for (const row of parameterRows) {
    requireText("docs/CURRENT_PARAMETERS.md", row, `generated parameter row is stale or missing: ${row}`);
  }

  const sessionMib = formatMib(contract.budgets.wasmSessionBytes);
  const sessionGib = contract.budgets.wasmSessionBytes / 1024 / 1024 / 1024;
  requireText(
    "docs/adr/0004-validated-production-backend.md",
    `| Wasm session budget | ${sessionMib} (${sessionGib} GiB) |`,
    "v0.2.0 amendment does not match the implemented Wasm session budget",
  );
  requireText(
    "docs/adr/0004-validated-production-backend.md",
    `| Imported annotation formats | ${contract.importedAnnotationSummary} |`,
    "v0.2.0 amendment does not match the imported annotation contract",
  );
  requireText(
    "docs/adr/0004-validated-production-backend.md",
    `| Browser sparse correction | ${contract.browserSparseCorrectionSummary} |`,
    "v0.2.0 amendment does not match the browser sparse-correction mode",
  );
  requireText(
    "docs/adr/0004-validated-production-backend.md",
    "Those two former release gates are complete",
    "browser-family and chromosome-scale gates are still presented as incomplete",
  );
  requireText(
    "docs/SCIENTIFIC_SPEC.md",
    "These routines are not part of the browser protocol, Wasm surface, ordinary\nweb build, production estimator, or release accuracy contract.",
    "validation-only sparse correction is not excluded from the production contract",
  );
  requireText(
    "docs/SCIENTIFIC_SPEC.md",
    "Sparse-correction fields are fixed\nto their disabled values in production.",
    "production ScientificConfig does not document disabled sparse fields",
  );
  forbidText(
    "docs/SCIENTIFIC_SPEC.md",
    "and optional bounded sparse sets.",
    "production FrozenAxis still claims optional bounded sparse sets",
  );
  requireText(
    "docs/VALIDATION_CONTRACT.md",
    "and v0.6.0 production cleanup plus export\nusability.",
    "completed product sequence does not include v0.6.0",
  );
  requireText(
    "docs/adr/0003-progressive-estimation-policy.md",
    "Superseded by ADR 0004. This record preserves the intermediate design",
    "superseded ADR status is ambiguous",
  );
  forbidText(
    "docs/adr/0004-validated-production-backend.md",
    "| Current contract | v0.2.0 state |",
    "historical v0.2.0 table is mislabeled as current",
  );
  requireText(
    "README.md",
    "Export nonzero, detailed current-view data as BEDPE together with an official-CLI JSON config",
    "current data export is missing from the feature summary",
  );
  requireText(
    "README.md",
    "Export the complete visible composition as PNG, SVG, or PDF",
    "current image export is missing from the feature summary",
  );
  requireText(
    "docs/SCIENTIFIC_SPEC.md",
    "A FASTA header is split at its first whitespace.",
    "FASTA identifier and description semantics are not documented",
  );
  requireText(
    "docs/USER_GUIDE.md",
    "Selectors use `SeqID_FileStem · Size`",
    "collision-safe sequence selector naming is not documented",
  );
  requireText(
    "docs/USER_GUIDE.md",
    "never writes quick-view estimates",
    "detailed-only export behavior is not documented",
  );
  requireText(
    "docs/USER_GUIDE.md",
    "heatmap legend in a separate right margin",
    "non-occluding export legend is not documented",
  );
  requireText(
    "docs/USER_GUIDE.md",
    "legend scale is linear in `ANI_c`",
    "linear export legend semantics are not documented",
  );
  requireText(
    "docs/USER_GUIDE.md",
    "six evenly spaced ticks",
    "uniform export legend ticks are not documented",
  );
  requireText(
    "docs/EXPORT_FORMATS.md",
    "x_seq_id",
    "compact CSV schema is not documented",
  );
  requireText(
    "docs/EXPORT_FORMATS.md",
    "direction = (F - R) / (F + R)",
    "export direction formula is not documented",
  );
  requireText(
    "docs/USER_GUIDE.md",
    "notice is owned by the browser",
    "browser-owned native picker warning is not documented",
  );
  requireText(
    "docs/USER_GUIDE.md",
    "Browsers without that API use their normal download behavior",
    "native save picker fallback is not documented",
  );

  const adr = readFileSync(
    join(repository, "docs/adr/0004-validated-production-backend.md"),
    "utf8",
  );
  const documentedColumnBlock = adr.match(
    /Current estimator-report columns: ([\s\S]*?)\.\n\n/,
  )?.[1];
  const documentedColumns = documentedColumnBlock
    ? [...documentedColumnBlock.matchAll(/`([^`]+)`/g)].map((match) => match[1])
    : [];
  if (documentedColumns.join("\t") !== contract.validationColumns.join("\t")) {
    failures.push(
      "docs/adr/0004-validated-production-backend.md: v0.2.1 estimator-report columns differ from the executable report schema",
    );
  }

  const review = readFileSync(
    join(repository, "docs/reviews/2026-08-28-v0.1-critical-review-response.md"),
    "utf8",
  );
  if (review.includes("1.5 GiB")) {
    failures.push("docs/reviews/2026-08-28-v0.1-critical-review-response.md: stale 1.5 GiB current-memory claim");
  }
  requireText(
    "docs/reviews/2026-08-28-v0.1-critical-review-response.md",
    `${sessionGib} GiB Wasm-session ceiling`,
    "current-memory disposition does not match the implemented session budget",
  );
  requireText(
    "docs/reviews/2026-08-28-v0.1-critical-review-response.md",
    "Implemented in v0.2.0",
    "feature-import disposition was not updated for v0.2.0",
  );
  requireText(
    "docs/reviews/2026-08-28-v0.1-critical-review-response.md",
    "always requests `sparseCorrection: false`",
    "browser sparse-correction disposition was not updated for v0.2.0",
  );
}

if (failures.length > 0) {
  throw new Error(`Documentation checks failed:\n${failures.map((failure) => `- ${failure}`).join("\n")}`);
}

console.log(
  `Checked ${markdown.length} generated Markdown documents, local links, and current implementation contracts.`,
);
